name: telegram-bot-message-dsl
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
  - Telegram.Bot.DSL
  - Telegram.Bot.DSL.TaggedContext
  - Telegram.Bot.DSL.Message

  dependencies:
  - base
  - telegram-bot-api
  - tagged
  - text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
