name: telegram-bot-message-dsl
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
  - Telegram.Bot.DSL
  - Telegram.Bot.DSL.Classes.HasTaggedContext
  - Telegram.Bot.DSL.Classes.IsCallbackData
  - Telegram.Bot.DSL.Classes.IsUnit
  - Telegram.Bot.DSL.Components.Button
  - Telegram.Bot.DSL.Components.ButtonLine
  - Telegram.Bot.DSL.Components.FmtText
  - Telegram.Bot.DSL.Components.Message
  - Telegram.Bot.DSL.Components.MessageLine
  - Telegram.Bot.DSL.Components.TextLine
  - Telegram.Bot.DSL.Conversions.AsMessage
  - Telegram.Bot.DSL.Conversions.AsMessageLine
  - Telegram.Bot.DSL.Conversions.AsTextLine
  - Telegram.Bot.DSL.Message
  - Telegram.Bot.DSL.Parsing
  - Telegram.Bot.DSL.TaggedContext
  - Telegram.Bot.DSL.Utils.RenameTag

  dependencies:
  - base
  - telegram-bot-api
  - tagged
  - text
  - defun-core

  language: GHC2021

  default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DerivingStrategies
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - NoStarIsType
  - PolyKinds
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
- -freduction-depth=0
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
